language: python
python:
- '2.7'
install:
- pip install --upgrade -r requirements.txt
script: pwd
deploy:
  provider: heroku
  api_key:
    secure: JZkm6JGuHbcrdotJumrZHyUd/2xg5tGmVbk69uNn2HJUrjNs3i3Hwqgsw7+gz0a8UTUxajckZpacmNSrZomr4CoiB/YyMEKgXxPFBihecaUdBlrkBwH82/w2bzJ/wwA4BKlfOZc1ujkABeZ6Uv0+4hYzrM9tdfJh75LwprwGmuM=
  app:
    master: ortoloco-dev
  on:
    repo: ortoloco/ortoloco
notifications:
  slack:
    secure: TkTCj0uHRsiLMLsR5ooLnDlLOPekLHZoW11bR+0r6GdjOZlTZEvUr3JW8r7e/DiJrsJs8uVq85d3czk649LoBnetFCZLWQKbTaLAX2E78Tc1Wd83z+Xg0/rZKNO/eWmePsf76BxPOYX43lOEzpAW308532u8DTB2Lyh8dzNpgvI=
